### ISSUE TITLE
12 hour time format

### ISSUE THREAD

**Issue by dalenoe** [0-1-0-1/weatherapp#2]
Is there an easy way to change the time format?

**Comment by 0-1-0-1** [comment]
It depends on what you understand by easy hahah
You will have to download the source, edit some lines and package it. I will add it soon :P

**Comment by 0-1-0-1** [comment]
I added it! To change 24 hour format to 12 hour format comment/delete lines 62 - 69 and uncomment lines 71 - 83 in **index.html**

**Comment by dalenoe** [comment]
Thanks so much. I've forked the project, as I have a few ideas (5/10 day forecasts and such) for it. I am hoping to start messing with it

**Comment by 0-1-0-1** [comment]
it will be greatly appreciated 🙏
